#!/usr/bin/env node

// Bronx Bot Dashboard Configuration Helper
const readline = require('readline');
const fs = require('fs').promises;
const mysql = require('mysql2/promise');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(query) {
    return new Promise(resolve => rl.question(query, resolve));
}

async function main() {
    console.log('🤖 Bronx Bot Dashboard Configuration Helper');
    console.log('==========================================\n');

    try {
        // Check if .env already exists
        try {
            await fs.access('.env');
            const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
            if (overwrite.toLowerCase() !== 'y') {
                console.log('Configuration cancelled.');
                process.exit(0);
            }
        } catch (error) {
            // .env doesn't exist, continue
        }

        console.log('📊 Database Configuration');
        console.log('Please enter your MariaDB/MySQL database details:\n');

        const dbHost = await question('Database Host (localhost): ') || 'localhost';
        const dbUser = await question('Database User (root): ') || 'root';
        const dbPassword = await question('Database Password: ');
        const dbName = await question('Database Name (bronxbot): ') || 'bronxbot';

        console.log('\n🔌 Testing database connection...');

        try {
            const connection = await mysql.createConnection({
                host: dbHost,
                user: dbUser,
                password: dbPassword,
                database: dbName
            });

            // Test connection
            await connection.execute('SELECT 1');
            console.log('✅ Database connection successful!');

            // Check if tables exist
            const [tables] = await connection.execute(`
                SELECT COUNT(*) as count 
                FROM information_schema.tables 
                WHERE table_schema = ? AND table_name = 'users'
            `, [dbName]);

            if (tables[0].count === 0) {
                console.log('⚠️  Warning: "users" table not found. Make sure the bot schema is loaded.');
            } else {
                console.log('✅ Database schema appears to be loaded correctly.');
            }

            await connection.end();

        } catch (error) {
            console.log(`❌ Database connection failed: ${error.message}`);
            const continueAnyway = await question('Continue with configuration anyway? (y/N): ');
            if (continueAnyway.toLowerCase() !== 'y') {
                process.exit(1);
            }
        }

        console.log('\n🌐 Server Configuration');
        const port = await question('Dashboard Port (3000): ') || '3000';

        // Generate random session secret
        const sessionSecret = Math.random().toString(36).substring(2) + 
                             Math.random().toString(36).substring(2);

        const envContent = `# Bronx Bot Dashboard Environment Configuration
# Generated by configuration helper

# Database Configuration
DB_HOST=${dbHost}
DB_USER=${dbUser}
DB_PASSWORD=${dbPassword}
DB_NAME=${dbName}

# Server Configuration  
PORT=${port}
NODE_ENV=production

# Session Security
SESSION_SECRET=${sessionSecret}

# Optional: Logging
LOG_LEVEL=info
`;

        await fs.writeFile('.env', envContent);
        console.log('\n✅ Configuration saved to .env file!');

        console.log('\n🚀 Next Steps:');
        console.log('1. Install dependencies: npm install');
        console.log('2. Start the dashboard: npm start');
        console.log('3. Open http://localhost:' + port + ' in your browser');
        console.log('\n📝 You can edit the .env file later to modify settings.');

        const startNow = await question('\n🚀 Start the dashboard now? (Y/n): ');
        if (startNow.toLowerCase() !== 'n') {
            const { spawn } = require('child_process');
            console.log('\nStarting dashboard...\n');
            
            // Check if node_modules exists
            try {
                await fs.access('node_modules');
            } catch (error) {
                console.log('📦 Installing dependencies first...');
                const npm = spawn('npm', ['install'], { stdio: 'inherit' });
                await new Promise((resolve) => npm.on('close', resolve));
            }

            const server = spawn('npm', ['start'], { stdio: 'inherit' });
            
            process.on('SIGINT', () => {
                console.log('\n👋 Shutting down dashboard...');
                server.kill();
                process.exit(0);
            });
        }

    } catch (error) {
        console.error('❌ Configuration failed:', error.message);
        process.exit(1);
    } finally {
        rl.close();
    }
}

main().catch(console.error);